server.port: 8999

management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.springframework.web.servlet: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true

spring:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE"
  application.name: ddalkkak
  datasource:
    url: ENC(Kt4iGTLuWzAs2oYbIldXhO19P3YTXnxs8DlQSR8EMAureTyAYRbye06FDZLVcwy9N7ZyvZf8aQw=)
    username: ENC(W8ysyKV/mEYrrDKfNW9qIA==)
    password: ENC(53bm72/Wdh2CEhaWVq4SwQ==)
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  devtools:
    livereload:
      enabled: true

  batch.jdbc.initialize-schema: always

jasypt:
  encryptor:
    password: ${DDALKKAK_PASSWORD}

slack:
  token: ENC(htaf5zKgrnwVstupDH5mduCKoJyBu6hf22AplAeGQPQ8NAxkRILMPTPdQylrkA2OaAN2OF3/q7rrBoRWIH/Z3kHUDPS6jsZH)
  team: T05PN75S6KB
---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb